# Anchorpoint Markup Language
# Predefined Variables: e.g. ${path}
# Environment Variables: e.g. ${MY_VARIABLE}
# Full documentation: https://docs.anchorpoint.app/api/intro

version: 1.0
action:
  name: Unreal

  version: 1
  id: ap::inc::project-settings
  category: user
  type: python
  author: Anchorpoint Software GmbH
  description: ""

  script: project_settings.py